- hosts: webservers

  tasks:
    - name: install git
      ansible.builtin.apt:
        name: git
        state: latest
      become: yes

    - name: add test users
      ansible.builtin.user:
        name: "{{ item }}"
        state: present
      become: yes  
      loop:
        - jaime
        - sansa
        - robert
      when: ansible_os_family != "Debian"

    - name: update git config
      ansible.builtin.template:
        src: /home/mike/hexlet-ans/git_conf/.gitconfig.j2
        dest: /home/{{item}}/.gitconfig
      become: yes
      loop:
        - jaime
        - sansa
        - robert

    - name: Set authorized key taken from file
      authorized_key:
        user: "{{item}}"
        state: present
        key: "{{ lookup('file', '/home/mike/hexlet-ans/git_conf/id_rsa.pub') }}" 
        manage_dir: yes
      become: yes
      loop:
        - jaime
        - sansa
        - robert